version: '3'
services:
  nudges:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - /usr/src/shop-fast-api
    ports:
      - 8001:8001
    depends_on:
      - db

  db:
    image: postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fast_api_shop